name: Pylint
#the pylint action will run at any push anywhere in te repository
on: [push]
#Use Ubuntu latest version  with python version "3.11" as an operating system for this action
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
 #Install the necessary libraries needed to run the action and install pylint using "pip install"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    # pylint every ".py" file in the repositiory and save the output as log file
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') > pylint_output.log
  # Upload the pylint output log as an artifact that can be downloaded from the GitHub Action page
    - name: Upload pylint output as artifact
      uses: actions/upload-artifact@v2
      with:
        name: pylint-output
        path: pylint_output.log
